python sample/edit.py ^
  --model_path "save\stage1_tiny_overfit_horse_locomotion_pose_v3\stage1_pretrain\model000034000.pt" ^
  --samples "dataset\truebones\zoo\truebones_processed\motions\Horse___Restless2_25.npy" ^
  --output_dir "outputs\edit_in_between_test" ^
  --edit_mode in_between ^
  --prefix_end 0.1 ^
  --suffix_start 0.9 ^
  --target_frames 60 ^
  --object_type Horse ^
  --num_samples 1 ^
  --num_repetitions 1 ^
  --seed 111